name: VTV Cần Thơ -> VTV10

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Record 3 hours
        run: |
          ffmpeg -loglevel warning -y \
          -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          -i "https://live.fptplay53.net/live/media/VTV_can_tho/live_hls_avc/VTV_can_tho-avc1_3800000=10000-mp4a_131600=20000.m3u8" \
          -map 0:v -map 0:a? \
          -c copy \
          -f mpegts \
          -t 10800 \
          output.ts

      - uses: actions/upload-artifact@v4
        with:
          name: test-3-hours
          path: output.ts
