name: Live YouTube PRO

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Live YouTube
        run: |
          ffmpeg -re -loglevel warning \
          -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          -thread_queue_size 512 \
          -i "https://live.fptplay53.net/live/media/VTV_can_tho/live_hls_avc/index.m3u8" \
          -map 0:v:0 -map 0:a:0? \
          -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p \
          -b:v 4500k -maxrate 4500k -bufsize 9000k \
          -g 50 -keyint_min 50 -sc_threshold 0 \
          -r 25 \
          -c:a aac -b:a 128k -ar 48000 \
          -af "aresample=async=1" \
          -f flv "rtmp://a.rtmp.youtube.com/live2/py7u-ewjm-36b0-auuj-51ea" \
          -t 100 \
          -flush_packets 1 \
          -shortest
